# Si existe la variable de entorno de Docker, la usa. Si no, usa localhost.
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/saludfinanciera}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sergiogutierrez}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:12345Guti}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# --- Configuración de IA Local (Ollama) ---
# En Docker usaremos el nombre del servicio "ollama", en local "localhost"
spring.ai.ollama.base-url=${SPRING_AI_OLLAMA_BASE_URL:http://localhost:11434}

# El modelo específico (asegúrate de que coincida con el que descargues en Docker)
spring.ai.ollama.chat.options.model=llama3.2:3b
spring.ai.ollama.chat.options.temperature=0.7

spring.jackson.deserialization.fail-on-unknown-properties=false