server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Proxy para el backend (opcional, pero ayuda a evitar problemas de CORS)
    location /api/ {
        proxy_pass http://salud-backend:8080/;
    }
}